<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111; }
        .header { border-bottom: 2px solid #eee; padding-bottom: 10px; margin-bottom: 20px; }
        .footer { border-top: 1px solid #eee; margin-top: 30px; padding-top: 10px; font-size: 10px; text-align: center; color: #555; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 8px; border-bottom: 1px solid #ddd; }
        th { background: #f5f5f5; text-align: left; }
        .right { text-align: right; }
        .total-row td { font-weight: bold; }
    </style>
</head>
<body>

@yield('content')

<div class="footer">
    Generated by GarageSuite
</div>

</body>
</html>
