<?php

return [
    'dalima_checkin_checkout_v1' => [
        // 1–20 (left column)
        1  => 'Registration No.',
        2  => 'Speedometer Reading',
        3  => 'Bonnet Star (M.B Vehicle)',
        4  => 'No. of External Badges',
        5  => 'Battery and Type',
        6  => 'Radiator cap',
        7  => 'Oil Filter Cap',
        8  => 'No. of Mirrors',
        9  => 'Number of Hub Caps',
        10 => 'No. of Keys/Holder',
        11 => 'Boot Star (M.B Vehicle)',
        12 => 'Fuel Tank & Lid lock',
        13 => 'Radio/Stereo/Make',
        14 => 'Aerial (Manual/Automatic)',
        15 => 'Interior Light',
        16 => 'Heater Switches/Knob',
        17 => 'Window Winder Handles',
        18 => 'Lock Knobs & Door Knobs',
        19 => 'EL/Clock',
        20 => 'Seat Belts',

        // 21–40 (middle column)
        21 => 'Head Rests',
        22 => 'Floor Carpet & Rubber Mats',
        23 => 'Cigar Lighter',
        24 => 'Extra Mats',
        25 => 'Boot Mats',
        26 => 'First Aid Box',
        27 => 'Fire Extinguisher',
        28 => 'Ash Trays',
        29 => 'Jack/Handle',
        30 => 'Radio Speakers',
        31 => 'Starter Motor',
        32 => 'Regulator',
        33 => 'Horns',
        34 => 'Washes Bag / Pump',
        35 => 'Blinker Lights',
        36 => 'Mud Flaps',
        37 => 'Ignition Distributor/Cap',
        38 => 'High Tension Leads',
        39 => 'Lights',
        40 => 'Spare Wheel (Make)',

        // 41–58 (right column)
        41 => 'Spot lights',
        42 => 'Windows',
        43 => 'Fuel Pump',
        44 => 'Fuel Level',
        45 => 'Control Box (Computer)',
        46 => 'Towing Rope',
        47 => 'Jumpers',
        48 => 'Rileys',
        49 => 'Radiator',
        50 => 'Pump Stick',
        51 => 'Spanners',
        52 => 'Pliers',
        53 => 'Steering Cap',
        54 => 'Master Cylinder',
        55 => 'Engine Lead Wires',
        56 => 'AC Pipe',
        57 => 'AC Cap',
        58 => 'Fuses',
    ],
];
